name: stremio-radics
services:
  stremio-radics:
    image: stremio-ncore-addon:custom
    environment:
      - ADDON_DIR=/addon
      - PORT=3000
      - TORRENT_SERVER_PORT=8080
      - NCORE_URL=https://ncore.pro
      - CINEMETA_URL=https://v3-cinemeta.strem.io
      - NCORE_USERNAME=
      - NCORE_PASSWORD=
      - DOWNLOADS_DIR=/downloads
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
      - target: 42069
        published: 42069
        protocol: tcp
      - target: 42069
        published: 42069
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/stremio-ncore-addon
        target: /addon
      - type: bind
        source: /mnt/hdd_main/stremio_downloads
        target: /downloads
x-casaos:
  scheme: http
  title:
    custom: Stremio nCore addon
  # Optional: if you serve the icon from your addon URL
  # icon: https://<your-addon-url>/stremio-ncore-addon-logo-rounded.png
